name: PHP Matrix Operations Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Adjust this to your PHP version
        ini-values: |
          extension=matrix_extension.so  # Initial attempt to load the extension

    - name: Show PHP configuration
      run: php -i | grep "extension_dir"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check for test data file
      run: |
        if [ ! -f "TEST/DATA/matrix_operations_results.json" ]; then
          echo "Test data file not found"
          exit 1
        fi

    - name: Check if matrix_extension.so exists
      id: check_extension
      run: |
        if [ -f "path/to/matrix_extension.so" ]; then  # Adjust the path as necessary
          echo "matrix_extension.so found."
          echo "add_extension=true" >> $GITHUB_ENV
        else
          echo "matrix_extension.so not found."
          echo "add_extension=false" >> $GITHUB_ENV
        fi

    - name: Add matrix_extension to php.ini if exists
      if: env.add_extension == 'true'
      run: |
        echo "extension=matrix_extension.so" >> $HOME/.php.ini  # Adjust path as necessary
        echo "matrix_extension added to php.ini"

    - name: Check if matrix_extension is loaded
      run: |
        if ! php -m | grep -q 'matrix_extension'; then
          echo "matrix_extension is not loaded, skipping tests that require it."
          exit 0  # Skip the test gracefully
        else
          echo "matrix_extension is loaded"
        fi

    - name: Run Matrix Operations Test
      run: php TEST/SCRIPT/matrix_operations_benchmark.php


